export ALLOW_MISSING_DEPENDENCIES=true

export FOX_VANILLA_BUILD=1
export FOX_VIRTUAL_AB_DEVICE=1
export OF_FORCE_PREBUILT_KERNEL=1
export FOX_BUILD_DEVICE=fogos
export OF_DEFAULT_KEYMASTER_VERSION=4.1
export OF_DYNAMIC_FULL_SIZE=5905580032

export FOX_MAINTAINER_PATCH_VERSION="1"
export FOX_VARIANT="A12"
export FOX_BUILD_TYPE="Stable"
